language: ruby
sudo: false
cache: bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - 2.6.1
gemfile:
  - gemfiles/Gemfile-rails.3.2.x
  - gemfiles/Gemfile-rails.4.0.x
  - gemfiles/Gemfile-rails.4.1.x
  - gemfiles/Gemfile-rails.4.2.x
  - gemfiles/Gemfile-rails.5.0.x
  - gemfiles/Gemfile-rails.5.1.x
  - Gemfile
before_install:
  - gem update --system
  - gem install bundler # https://github.com/travis-ci/travis-ci/issues/9333
matrix:
 exclude:
   - rvm: 1.9.3
     gemfile: Gemfile
   - rvm: 1.9.3
     gemfile: gemfiles/Gemfile-rails.5.0.x
   - rvm: 1.9.3
     gemfile: gemfiles/Gemfile-rails.5.1.x
   - rvm: 2.0.0
     gemfile: Gemfile
   - rvm: 2.0.0
     gemfile: gemfiles/Gemfile-rails.5.0.x
   - rvm: 2.0.0
     gemfile: gemfiles/Gemfile-rails.5.1.x
   - rvm: 2.1.10
     gemfile: Gemfile
   - rvm: 2.1.10
     gemfile: gemfiles/Gemfile-rails.5.0.x
   - rvm: 2.1.10
     gemfile: gemfiles/Gemfile-rails.5.1.x
   - rvm: 2.2.10
     gemfile: gemfiles/Gemfile-rails.3.2.x
   - rvm: 2.3.7
     gemfile: gemfiles/Gemfile-rails.3.2.x
   - rvm: 2.4.4
     gemfile: gemfiles/Gemfile-rails.3.2.x
   - rvm: 2.5.1
     gemfile: gemfiles/Gemfile-rails.3.2.x
   - rvm: 2.6.1
     gemfile: gemfiles/Gemfile-rails.3.2.x

notifications:
  email: false
  campfire:
    on_success: change
    on_failure: always
    rooms:
      - secure: "PexwWrMM6bkEVPt5b28GGSF5ThaUX5mRgY/8fK3kAXgGolvXoZdF6XZt8zE1\nTbE+AMQLayILXOFRd1bTL537Qf2Y63n6arKH19t9GBBdqZo1ZveVOca0qiSB\n0reSG8sauQXUA95ygEqhWd6VYkDRu1oJpwgsDv47igawbqAOrgE="
